# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Enable Python Scripts
python_script:

logger:
  default: info

input_select:
  override_livingroom_automations:
    name: Living Room overrided automations list
    options: 
      - placeholder

input_boolean:
  override_livingroom_toggle:
    name: Override Rec Room Toggle

timer:
  livingroom_idle_timer:
    name: Living Room Lights Idle Timer
    restore: true
  override_livingroom_timer:
    name: Override Active Living Room Automations
    restore: true
